name: Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: yarn policies set-version berry
    - run: yarn set version latest
    - run: yarn config set nodeLinker node-modules
    - run: yarn plugin import @yarnpkg/plugin-interactive-tools
    - run: yarn plugin import @yarnpkg/plugin-workspace-tools
    - run: yarn
    - run: yarn all:build
      env:
        CI: true
